### ISSUE TITLE
Migrate from `traverse` to `neotraverse`

### ISSUE THREAD

**Issue by trivikr** [Worldline-Global-Collect/connect-sdk-nodejs#1]
**Is your feature request related to a problem? Please describe.**

The [Ecosystem Performance](https://e18e.dev/) was formed in July 2024 to cleanup, speedup, levelup the JavaScript Ecosystem.
Socket Security team wrote a blog post about it https://socket.dev/blog/javascript-community-launches-e18e-initiative-to-improve-ecosystem-performance

On the e18e cleanup channel on Discord, multiple solutions are being discussed. One of them is to replace `traverse` with `neotraverse`, which reduces install size by around 3.5 MB and number of dependencies by 65.
For details, check blog post https://puruvj.dev/blog/forking-and-fixing-traverse

The Worldline-Global-Collect/connect-sdk-nodejs depends on traverse
https://github.com/Worldline-Global-Collect/connect-sdk-nodejs/blob/154c01e230c8001fc90c1c32559ad90a68d7939d/package.json#L38

**Describe the solution you'd like**

Migrate from `traverse` to `neotraverse`

There's a codemod available in https://github.com/es-tooling/module-replacements-codemods to migrate from traverse to neotraverse

**Comment by WorldlineSolutionsIO** [comment]
Thanks for informing us about this new dependency. However, after your comment we have investigated the use of the `traverse` dependency, and have decided we can get rid of it completely. The next release will not depend on either `traverse` or `neotraverse`.

**Comment by trivikr** [comment]
> The next release will not depend on either `traverse` or `neotraverse`.

That's even better! Thank you.

**Comment by WorldlineSolutionsIO** [comment]
A new version has just been released that no longer has a dependency on `traverse`.
